name: test

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:

    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'    

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        
    - name: Install dependencies
      run: make install

    - name: Run test
      run: make test
